# in .cargo/config.toml

[unstable]
# enable the inter complier function about memory(memset, memcpy) 
build-std-features = ["compiler-builtins-mem"] 
# core is rust kernel lib, no depend on the OS 
# compiler_builtins is complier built-in function library
build-std = ["core", "compiler_builtins"]

[build]
target = "x86_64-blog_os.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
